### PR TITLE
Simplify docker; build from checkout

### PR DESCRIPTION
**Pull request by sebbASF**
This works for me

### CODE REVIEW

**Comment by dave2wave** [comment]
1. In the two phase Dockerfile cmake was not included in the final image. This new Dockerfile creates an image that is 642MB while the master branch image is 413MB.

2. It is better that the /root/.authtokens be missing and the error message seen than for the file to be present but missing the twitter bearer token. It would be good to be able to include an ARG that would copy a .authtokens file into the image.

**Comment by dave2wave** [comment]
I've added support for .authtokens with instructions included at the top of the Dockerfile

**Comment by sebbASF** [comment]
-1 
I think the authtokens belong with the site, not the shared software, so should not be in the docker image.

**Comment by dave2wave** [comment]
The authtokens do not belong with a site. They are secrets and are not open source.

See https://github.com/apache/www-site/issues/8

**Comment by dave2wave** [comment]
Also - https://github.com/apache/infrastructure-p6/blob/production/modules/buildbot_node/manifests/authtokens.pp

**Comment by dave2wave** [comment]
So - perhaps we don't have .authtokens in the image until a build is initiated that needs them.

This means that the ENTRYPOINT needs work to accept an optional .authtokens file.

This needs some thought.

**Comment by dave2wave** [comment]
I think 44ee979 should be reverted as well.

**Comment by sebbASF** [comment]
One possible method is to create the following link in the Dockerfile:

RUN ln -s /site/.authtokens /root/.authtokens

Then create the .authtokens file in the local checkout (which is mapped to /site) before running the pelican build.

**Comment by sebbASF** [comment]
An alternative would be to create a named volume which contains the token.
Then mount as (say) /auth, with appropriate adjustment to root link
Or even mount as (say) /site/auth, adjusting the link again.
This would allow the user to either create the token directly under the site, or mount it from the named volume.

**Comment by dave2wave** [comment]
This works for me. I squash and merge in the morning.

**Pull request merged**
